export const WORD_LIST = [
  // Easy words (4-6 letters)
  { word: "cat", hint: "A popular pet that purrs" },
  { word: "dog", hint: "Man's best friend" },
  { word: "sun", hint: "Center of our solar system" },
  { word: "moon", hint: "Earth's natural satellite" },
  { word: "book", hint: "A written or printed work" },
  { word: "cake", hint: "A sweet baked dessert" },
  { word: "bird", hint: "A feathered animal that flies" },
  { word: "fish", hint: "Lives in water with scales and fins" },
  { word: "tree", hint: "A tall plant with a wooden trunk" },
  { word: "house", hint: "A place where people live" },
  { word: "apple", hint: "A common fruit, often red or green" },
  { word: "water", hint: "Essential liquid for life" },
  { word: "chair", hint: "Something you sit on" },
  { word: "table", hint: "A piece of furniture with a flat top" },
  { word: "clock", hint: "Tells the time" },
  { word: "music", hint: "Sounds arranged to create melodies" },
  { word: "bread", hint: "A staple food made from flour" },
  { word: "pizza", hint: "Italian dish with toppings" },
  { word: "beach", hint: "Sandy shore by the ocean" },
  { word: "grass", hint: "Green plants in lawns" },
  { word: "ant", hint: "Small insect that lives in colonies" },
  { word: "car", hint: "Four-wheeled motor vehicle" },
  { word: "hat", hint: "Head covering for protection or fashion" },
  { word: "pen", hint: "Writing instrument using ink" },
  { word: "cup", hint: "Small container for drinking" },
  { word: "map", hint: "Representation of an area" },
  { word: "bed", hint: "Furniture for sleeping" },
  { word: "key", hint: "Used to open locks" },
  { word: "egg", hint: "Oval reproductive body laid by birds" },
  { word: "jam", hint: "Sweet spread made from fruit" },
  { word: "fox", hint: "Small wild canine with a bushy tail" },
  { word: "lip", hint: "Fleshy part around the mouth" },
  { word: "nut", hint: "Hard-shelled fruit" },
  { word: "owl", hint: "Nocturnal bird of prey" },
  { word: "pig", hint: "Domesticated farm animal" },
  { word: "rat", hint: "Long-tailed rodent" },
  { word: "saw", hint: "Tool for cutting wood" },
  { word: "toy", hint: "Plaything for children" },
  { word: "van", hint: "Large vehicle for transporting goods" },
  { word: "zoo", hint: "Place where animals are kept for exhibition" },
  { word: "bike", hint: "Two-wheeled vehicle powered by pedals" },
  { word: "ball", hint: "Round object used in games" },
  { word: "desk", hint: "Furniture for writing or working" },
  { word: "door", hint: "Movable barrier at an entrance" },
  { word: "fire", hint: "Combustion producing heat and light" },
  { word: "gold", hint: "Precious yellow metal" },
  { word: "hand", hint: "End of the arm used for grasping" },
  { word: "iron", hint: "Strong metallic element" },
  { word: "jump", hint: "Spring off the ground" },
  { word: "kite", hint: "Toy flown in the wind on a string" },
  { word: "lamp", hint: "Device producing light" },
  { word: "milk", hint: "Nutritious white liquid from mammals" },
  { word: "nose", hint: "Facial organ for smelling and breathing" },
  { word: "oven", hint: "Enclosed compartment for cooking" },
  { word: "rain", hint: "Precipitation from clouds" },
  { word: "ship", hint: "Large watercraft" },
  { word: "snow", hint: "Frozen precipitation" },
  { word: "star", hint: "Luminous celestial body" },
  { word: "tent", hint: "Portable shelter of fabric" },
  { word: "wolf", hint: "Wild canine predator" },
  { word: "yarn", hint: "Fiber used for knitting" },
  { word: "angel", hint: "Heavenly messenger" },
  { word: "baker", hint: "Person who makes bread" },
  { word: "candy", hint: "Sweet food made with sugar" },
  { word: "dance", hint: "Rhythmic body movements to music" },
  { word: "earth", hint: "Our planet" },
  { word: "fairy", hint: "Mythical magical creature" },
  { word: "grape", hint: "Small sweet fruit growing in clusters" },
  { word: "happy", hint: "Feeling of joy" },
  { word: "igloo", hint: "Dome-shaped Inuit snow house" },
  { word: "juice", hint: "Liquid extracted from fruits" },
  { word: "koala", hint: "Australian tree-dwelling marsupial" },
  { word: "lemon", hint: "Yellow citrus fruit" },
  { word: "money", hint: "Medium of exchange" },
  { word: "night", hint: "Time between sunset and sunrise" },
  { word: "ocean", hint: "Vast body of salt water" },
  { word: "piano", hint: "Keyboard musical instrument" },
  { word: "queen", hint: "Female monarch" },
  { word: "river", hint: "Large natural stream of water" },
  { word: "smile", hint: "Facial expression showing pleasure" },
  { word: "tiger", hint: "Large striped feline" },
  { word: "uncle", hint: "Brother of one's parent" },
  { word: "vase", hint: "Decorative container for flowers" },
  { word: "watch", hint: "Timepiece worn on the wrist" },
  { word: "zebra", hint: "African wild horse with stripes" },
  { word: "anchor", hint: "Device to moor a vessel" },
  { word: "bottle", hint: "Container with a narrow neck" },
  { word: "camera", hint: "Device for taking photographs" },
  { word: "dollar", hint: "Basic monetary unit in several countries" },
  { word: "eleven", hint: "Number between ten and twelve" },
  { word: "flower", hint: "Reproductive structure of plants" },
  { word: "garden", hint: "Space for cultivating plants" },
  { word: "hammer", hint: "Tool for pounding nails" },
  { word: "island", hint: "Land surrounded by water" },
  { word: "jacket", hint: "Outer garment for the upper body" },
  { word: "kitten", hint: "Young cat" },
  { word: "ladder", hint: "Climbing equipment with rungs" },
  { word: "mirror", hint: "Reflective surface" },
  { word: "needle", hint: "Thin pointed tool for sewing" },
  { word: "orange", hint: "Citrus fruit and color" },
  { word: "parrot", hint: "Colorful talking bird" },
  { word: "rocket", hint: "Vehicle that travels through space" },
  { word: "school", hint: "Institution for education" },
  { word: "tomato", hint: "Red edible fruit used as vegetable" },
  { word: "violin", hint: "Stringed musical instrument" },
  { word: "window", hint: "Opening in a wall to admit light" },
  { word: "yellow", hint: "Color of sunshine" },

  // Medium words (7-9 letters)
  { word: "computer", hint: "Electronic device for processing data" },
  { word: "xylophone", hint: "Musical instrument with wooden bars" },
  { word: "elephant", hint: "Large mammal with a trunk" },
  { word: "mountain", hint: "A very high natural elevation" },
  { word: "birthday", hint: "Annual celebration of one's birth" },
  { word: "hospital", hint: "Medical care facility" },
  { word: "library", hint: "Building with collections of books" },
  { word: "baseball", hint: "Sport with a bat and ball" },
  { word: "dinosaur", hint: "Extinct reptiles that lived millions of years ago" },
  { word: "painting", hint: "Art created with colors on a surface" },
  { word: "chocolate", hint: "Sweet treat made from cocoa" },
  { word: "umbrella", hint: "Used for protection from rain" },
  { word: "keyboard", hint: "Used to input text into a computer" },
  { word: "airplane", hint: "Flying transportation vehicle" },
  { word: "butterfly", hint: "Insect with colorful wings" },
  { word: "sandwich", hint: "Food with ingredients between bread slices" },
  { word: "rainbow", hint: "Colorful arc in the sky after rain" },
  { word: "festival", hint: "Celebration or special event" },
  { word: "vacation", hint: "A period of leisure and recreation" },
  { word: "swimming", hint: "Moving through water using bodily movements" },
  { word: "universe", hint: "All of space and everything in it" },
  { word: "airport", hint: "Place where aircraft take off and land" },
  { word: "bicycle", hint: "Two-wheeled pedal-powered vehicle" },
  { word: "coconut", hint: "Large brown seed of a tropical palm" },
  { word: "diamond", hint: "Hard precious stone" },
  { word: "eleven", hint: "Number after ten" },
  { word: "firefly", hint: "Insect that produces light" },
  { word: "giraffe", hint: "Tall African animal with a long neck" },
  { word: "hamburger", hint: "Ground meat patty in a bun" },
  { word: "internet", hint: "Global computer network" },
  { word: "jellyfish", hint: "Gelatinous sea creature" },
  { word: "keyboard", hint: "Set of piano keys or computer input device" },
  { word: "lightning", hint: "Electrical discharge during a storm" },
  { word: "mushroom", hint: "Fungal growth often used as food" },
  { word: "notebook", hint: "Book of blank pages for writing" },
  { word: "octopus", hint: "Eight-armed sea creature" },
  { word: "penguin", hint: "Flightless Antarctic bird" },
  { word: "quilt", hint: "Bed covering made of padding" },
  { word: "raincoat", hint: "Waterproof outer garment" },
  { word: "scissors", hint: "Cutting tool with two blades" },
  { word: "telescope", hint: "Optical instrument for viewing distant objects" },
  { word: "umbrella", hint: "Canopy for protection against rain" },
  { word: "volcano", hint: "Mountain that erupts lava" },
  { word: "waterfall", hint: "Stream flowing over a cliff" },
  { word: "xylophone", hint: "Percussion instrument with wooden bars" },
  { word: "yesterday", hint: "The day before today" },
  { word: "zeppelin", hint: "Large German airship" },
  { word: "adventure", hint: "Exciting or dangerous experience" },
  { word: "backpack", hint: "Bag carried on the back" },
  { word: "calendar", hint: "System for organizing days" },
  { word: "dinosaur", hint: "Prehistoric reptile" },
  { word: "exercise", hint: "Physical activity for health" },
  { word: "football", hint: "Popular team sport" },
  { word: "gymnasium", hint: "Room for physical exercise" },
  { word: "happiness", hint: "State of being happy" },
  { word: "iceberg", hint: "Large floating mass of ice" },
  { word: "jigsaw", hint: "Puzzle with interlocking pieces" },
  { word: "kangaroo", hint: "Australian hopping marsupial" },
  { word: "lighthouse", hint: "Tower with a bright light for navigation" },
  { word: "mountain", hint: "Large natural elevation" },
  { word: "necklace", hint: "Jewelry worn around the neck" },
  { word: "overalls", hint: "Protective trousers with a bib" },
  { word: "pineapple", hint: "Tropical fruit with spiky skin" },
  { word: "question", hint: "Sentence seeking information" },
  { word: "raspberry", hint: "Small red edible berry" },
  { word: "sandwich", hint: "Food between slices of bread" },
  { word: "telephone", hint: "Device for voice communication" },
  { word: "universe", hint: "All existing matter and space" },
  { word: "vegetable", hint: "Edible plant or part of a plant" },
  { word: "whisper", hint: "Speak very softly" },
  { word: "xylophone", hint: "Musical instrument with wooden bars" },
  { word: "yogurt", hint: "Dairy product from fermented milk" },
  { word: "zucchini", hint: "Green summer squash" },
  { word: "balloon", hint: "Inflatable rubber bag" },
  { word: "carnival", hint: "Traveling amusement show" },
  { word: "delivery", hint: "Bringing goods to a destination" },
  { word: "elephant", hint: "Large mammal with a trunk" },
  { word: "firework", hint: "Explosive device for display" },
  { word: "grandma", hint: "Mother of one's parent" },
  { word: "hospital", hint: "Medical treatment facility" },
  { word: "inventor", hint: "Creator of new devices" },
  { word: "jewelry", hint: "Personal ornaments" },
  { word: "kingdom", hint: "Country ruled by a monarch" },
  { word: "lemonade", hint: "Sweetened lemon drink" },
  { word: "mermaid", hint: "Mythical sea creature" },
  { word: "newspaper", hint: "Printed publication of news" },
  { word: "orchestra", hint: "Large instrumental ensemble" },
  { word: "popcorn", hint: "Puffed corn kernels" },
  { word: "quicksand", hint: "Loose wet sand that engulfs" },
  { word: "restaurant", hint: "Place to eat out" },
  { word: "sunshine", hint: "Direct sunlight" },
  { word: "tornado", hint: "Violently rotating wind column" },
  { word: "upstairs", hint: "Higher floor of a building" },
  { word: "vacation", hint: "Leisure time away from work" },
  { word: "wildlife", hint: "Undomesticated animals" },
  { word: "xylophone", hint: "Percussion instrument" },
  { word: "yellow", hint: "Color of ripe lemons" },
  { word: "zookeeper", hint: "Person who cares for zoo animals" },

  // Hard words (10+ letters)
  { word: "photography", hint: "Art of capturing images" },
  { word: "mathematics", hint: "Study of numbers and quantities" },
  { word: "celebration", hint: "Act of marking a special occasion" },
  { word: "architecture", hint: "Art and science of designing buildings" },
  { word: "encyclopedia", hint: "Reference work with articles on various topics" },
  { word: "communication", hint: "Exchange of information" },
  { word: "constellation", hint: "Group of stars forming a pattern" },
  { word: "perspective", hint: "A particular way of viewing things" },
  { word: "imagination", hint: "Ability to form mental images" },
  { word: "temperature", hint: "Measure of heat or cold" },
  { word: "entertainment", hint: "Activities that provide amusement" },
  { word: "environment", hint: "Surroundings or conditions" },
  { word: "technology", hint: "Application of scientific knowledge" },
  { word: "laboratory", hint: "Place equipped for scientific research" },
  { word: "opportunity", hint: "Favorable time or chance" },
  { word: "personality", hint: "Individual's characteristic patterns" },
  { word: "revolution", hint: "Fundamental change in power or structure" },
  { word: "information", hint: "Facts provided or learned" },
  { word: "government", hint: "System by which a state is governed" },
  { word: "education", hint: "Process of receiving or giving instruction" },
  { word: "abomination", hint: "Thing that causes disgust" },
  { word: "basketball", hint: "Team sport with hoops" },
  { word: "celebration", hint: "Joyful occasion" },
  { word: "determination", hint: "Firmness of purpose" },
  { word: "extravaganza", hint: "Elaborate spectacular event" },
  { word: "fascinating", hint: "Extremely interesting" },
  { word: "grandfather", hint: "Father of one's parent" },
  { word: "helicopter", hint: "Rotary-wing aircraft" },
  { word: "imagination", hint: "Creative mental faculty" },
  { word: "jackhammer", hint: "Pneumatic drilling tool" },
  { word: "kaleidoscope", hint: "Optical toy with mirrors" },
  { word: "laboratory", hint: "Research facility" },
  { word: "magnificent", hint: "Extremely beautiful" },
  { word: "neighborhood", hint: "Local community area" },
  { word: "opportunity", hint: "Favorable chance" },
  { word: "photography", hint: "Art of taking pictures" },
  { word: "quadruple", hint: "Multiply by four" },
  { word: "refrigerator", hint: "Appliance for cooling food" },
  { word: "strawberry", hint: "Sweet red berry" },
  { word: "thermometer", hint: "Temperature measuring device" },
  { word: "understanding", hint: "Comprehension" },
  { word: "volleyball", hint: "Team sport with a net" },
  { word: "watermelon", hint: "Large juicy fruit" },
  { word: "xylography", hint: "Art of wood engraving" },
  { word: "yellowstone", hint: "Famous national park" },
  { word: "zoological", hint: "Relating to animals" },
  { word: "appreciate", hint: "Recognize the value of" },
  { word: "butterfly", hint: "Flying insect with colorful wings" },
  { word: "chocolate", hint: "Sweet food from cacao" },
  { word: "discovery", hint: "Finding something new" },
  { word: "electricity", hint: "Form of energy" },
  { word: "friendship", hint: "Bond between friends" },
  { word: "generation", hint: "Group born at same time" },
  { word: "happiness", hint: "State of being happy" },
  { word: "importance", hint: "Quality of being significant" },
  { word: "jungle", hint: "Tropical forest" },
  { word: "knowledge", hint: "Information and skills" },
  { word: "landscape", hint: "Visible features of land" },
  { word: "mysterious", hint: "Difficult to understand" },
  { word: "nutrition", hint: "Process of nourishing" },
  { word: "obligation", hint: "Duty or commitment" },
  { word: "permission", hint: "Authorization" },
  { word: "qualification", hint: "Competence for a role" },
  { word: "respiration", hint: "Breathing" },
  { word: "satisfaction", hint: "Fulfillment" },
  { word: "temperature", hint: "Degree of heat" },
  { word: "university", hint: "Higher education institution" },
  { word: "vegetation", hint: "Plant life" },
  { word: "wilderness", hint: "Uncultivated land" },
  { word: "xenophobia", hint: "Fear of foreigners" },
  { word: "youngster", hint: "Young person" },
  { word: "zoologist", hint: "Animal scientist" },
  { word: "accomplish", hint: "Achieve successfully" },
  { word: "brilliant", hint: "Exceptionally clever" },
  { word: "comfortable", hint: "Providing physical ease" },
  { word: "difference", hint: "Point or way of being unlike" },
  { word: "experience", hint: "Practical contact with events" },
  { word: "frightening", hint: "Making afraid" },
  { word: "government", hint: "Governing body of a nation" },
  { word: "historical", hint: "Concerning past events" },
  { word: "investment", hint: "Committing money for profit" },
  { word: "journalist", hint: "News reporter" },
  { word: "kindergarten", hint: "Preschool for young children" },
  { word: "literature", hint: "Written artistic works" },
  { word: "mathematics", hint: "Study of numbers" },
  { word: "noticeable", hint: "Easily seen or noticed" },
  { word: "observation", hint: "Action of observing" },
  { word: "particular", hint: "Specific item or detail" },
  { word: "questionnaire", hint: "Set of written questions" },
  { word: "recommend", hint: "Suggest favorably" },
  { word: "significant", hint: "Sufficiently important" },
  { word: "transportation", hint: "Moving people/goods" },
  { word: "unbelievable", hint: "Difficult to accept as true" },
  { word: "valuable", hint: "Worth a great deal" },
  { word: "wonderful", hint: "Extremely good" },
  { word: "xenon", hint: "Chemical element with symbol Xe" },
  { word: "yesterday", hint: "The day before today" },
  { word: "zeppelin", hint: "Large German airship" },

  // Phrase words
  { word: "ice cream", hint: "Cold dairy dessert" },
  { word: "high five", hint: "Hand slap greeting" },
  { word: "new york", hint: "Major US city" },
  { word: "outer space", hint: "Beyond Earth's atmosphere" },
  { word: "black hole", hint: "Region of spacetime with extreme gravity" },
  { word: "video game", hint: "Interactive electronic entertainment" },
  { word: "social media", hint: "Online platforms for sharing content" },
  { word: "global warming", hint: "Long-term heating of Earth's climate" },
  { word: "artificial intelligence", hint: "Computer systems able to perform tasks requiring human intelligence" },
  { word: "solar system", hint: "Sun and the objects orbiting it" },
  { word: "hot dog", hint: "Grilled sausage in a bun" },
  { word: "thank you", hint: "Polite expression of gratitude" },
  { word: "good night", hint: "Evening farewell" },
  { word: "happy birthday", hint: "Celebration greeting" },
  { word: "ice cube", hint: "Small block of frozen water" },
  { word: "junk food", hint: "Unhealthy snack items" },
  { word: "key chain", hint: "Ring for holding keys" },
  { word: "love letter", hint: "Romantic written message" },
  { word: "mail box", hint: "Container for incoming mail" },
  { word: "night light", hint: "Small comforting illumination" },
  { word: "open house", hint: "Real estate viewing event" },
  { word: "post office", hint: "Mail handling facility" },
  { word: "quick sand", hint: "Loose wet sand that engulfs" },
  { word: "rain drop", hint: "Single unit of precipitation" },
  { word: "snow ball", hint: "Pressed snow in spherical form" },
  { word: "tea cup", hint: "Small cup for drinking tea" },
  { word: "under water", hint: "Beneath the surface of water" },
  { word: "video tape", hint: "Magnetic tape for recording video" },
  { word: "web page", hint: "Single document on the internet" },
  { word: "x ray", hint: "Electromagnetic radiation for imaging" },
  { word: "yellow pages", hint: "Telephone directory for businesses" },
  { word: "zip code", hint: "Postal delivery code" },
  { word: "apple pie", hint: "Classic American dessert" },
  { word: "bus stop", hint: "Designated place to board buses" },
  { word: "coffee shop", hint: "Establishment serving coffee" },
  { word: "dream catcher", hint: "Native American protective charm" },
  { word: "emergency room", hint: "Hospital department for urgent care" },
  { word: "fire station", hint: "Fire department headquarters" },
  { word: "garden hose", hint: "Flexible tube for watering" },
  { word: "high school", hint: "Secondary education institution" },
  { word: "ice skating", hint: "Gliding on ice with blades" },
  { word: "jazz music", hint: "Improvisational musical genre" },
  { word: "kitten", hint: "Young domestic cat" },
  { word: "lemon tree", hint: "Citrus fruit bearing plant" },
  { word: "moon light", hint: "Illumination from the moon" },
  { word: "north pole", hint: "Northernmost point on Earth" },
  { word: "orange juice", hint: "Beverage from squeezed oranges" },
  { word: "peanut butter", hint: "Spread made from ground peanuts" },
  { word: "queen bee", hint: "Reproductive female in a hive" },
  { word: "rock climbing", hint: "Sport of scaling rock formations" },
  { word: "south pole", hint: "Southernmost point on Earth" },
  { word: "traffic light", hint: "Signal controlling road traffic" },
  { word: "umbrella stand", hint: "Holder for wet umbrellas" },
  { word: "volleyball", hint: "Team sport with a net" },
  { word: "water bottle", hint: "Container for drinking water" },
  { word: "xylophone", hint: "Percussion instrument" },
  { word: "yoga mat", hint: "Cushioned surface for exercises" },
  { word: "zebra crossing", hint: "Pedestrian crosswalk with stripes" },
  { word: "air conditioner", hint: "Appliance for cooling air" },
  { word: "birthday cake", hint: "Dessert for birthday celebrations" },
  { word: "christmas tree", hint: "Decorated evergreen for holidays" },
  { word: "diamond ring", hint: "Jewelry with precious stone" },
  { word: "electric guitar", hint: "Amplified string instrument" },
  { word: "french fries", hint: "Deep-fried potato strips" },
  { word: "golden retriever", hint: "Popular dog breed" },
  { word: "halloween costume", hint: "Outfit worn for October holiday" },
  { word: "ice cream cone", hint: "Edible holder for frozen dessert" },
  { word: "jigsaw puzzle", hint: "Picture made of interlocking pieces" },
  { word: "knight", hint: "Medieval mounted soldier" },
  { word: "lemonade stand", hint: "Child-run beverage business" },
  { word: "mountain bike", hint: "Sturdy bicycle for rough terrain" },
  { word: "newspaper stand", hint: "Display for periodicals" },
  { word: "olympic games", hint: "International sporting event" },
  { word: "piano lesson", hint: "Instruction in keyboard playing" },
  { word: "quantum physics", hint: "Study of subatomic particles" },
  { word: "roller coaster", hint: "Amusement park thrill ride" },
  { word: "strawberry shortcake", hint: "Dessert with berries and cream" },
  { word: "tennis court", hint: "Playing area for racquet sport" },
  { word: "united nations", hint: "International organization" },
  { word: "vacuum cleaner", hint: "Device for sucking up dirt" },
  { word: "windsurfing", hint: "Water sport with sailboard" },
  { word: "yellow submarine", hint: "Beatles song and animated film" },
  { word: "zoo keeper", hint: "Person who cares for zoo animals" }
];